version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
  api:
    build: "./api"
    container_name: node-container
    environment:
      - MONGO_URL=mongodb://root:123@mongo:27017/admin
      - PORT=3000
    restart: always
    volumes:
      - ./api:/api/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
